include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    missing_required_param: error
    missing_return: error
    unused_import: warning

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_conditional_assignment
    - always_declare_return_types
